"use client";
import { useEffect, useState } from "react";
import api from "@/lib/api";
import { useRouter } from "next/navigation";


export default function CreateUserPage() {
  const router = useRouter();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState(""); // optional
  const [phone, setPhone] = useState("");
  const [role, setRole] = useState("Student");
  const [departmentId, setDepartmentId] = useState("");
  const [departments, setDepartments] = useState([]);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) return router.push("/login");

    api.get("/admin/departments/all", { headers: { Authorization: `Bearer ${token}` } })
      .then(res => setDepartments(res.data.departments))
      .catch(() => {
        setError("Failed to load departments");
      });
  }, []);

  const validateEmail = (e) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e);

  const handleSubmit = async (ev) => {
    ev.preventDefault();
    setMessage("");
    setError("");

    if (!name || !email || !role) {
      setError("Please fill required fields");
      return;
    }
    if (!validateEmail(email)) {
      setError("Invalid email");
      return;
    }

    const token = localStorage.getItem("token");
    if (!token) return router.push("/login");

    try {
      const payload = {
        name,
        email,
        password: password || undefined,
        phone,
        role,
        departmentId: departmentId || undefined
      };

      const res = await api.post("/admin/users/create", payload, { headers: { Authorization: `Bearer ${token}` } });

      setMessage(res.data.message || "User created");
      // optional: clear form
      setName(""); setEmail(""); setPassword(""); setPhone(""); setDepartmentId(""); setRole("Student");
    } catch (err) {
      setError(err.response?.data?.message || "Create user failed");
    }
  };

  return (
    <div className="max-w-2xl mx-auto mt-10 bg-white p-8 shadow rounded-xl">
      <h1 className="text-2xl font-bold mb-4">Create User</h1>

      {message && <div className="mb-4 text-green-700">{message}</div>}
      {error && <div className="mb-4 text-red-600">{error}</div>}

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block font-medium">Name *</label>
          <input className="w-full border p-2 rounded" value={name} onChange={e => setName(e.target.value)} required />
        </div>

        <div>
          <label className="block font-medium">Email *</label>
          <input className="w-full border p-2 rounded" value={email} onChange={e => setEmail(e.target.value)} required />
        </div>

        <div>
          <label className="block font-medium">Password (optional — autogenerated if left blank)</label>
          <input type="password" className="w-full border p-2 rounded" value={password} onChange={e => setPassword(e.target.value)} />
        </div>

        <div>
          <label className="block font-medium">Phone</label>
          <input className="w-full border p-2 rounded" value={phone} onChange={e => setPhone(e.target.value)} />
        </div>

        <div>
          <label className="block font-medium">Role *</label>
          <select className="w-full border p-2 rounded" value={role} onChange={e => setRole(e.target.value)}>
            <option value="Student">Student</option>
            <option value="Professor">Professor</option>
            <option value="HOD">HOD</option>
          </select>
        </div>

        <div>
          <label className="block font-medium">Department</label>
          <select className="w-full border p-2 rounded" value={departmentId} onChange={e => setDepartmentId(e.target.value)}>
            <option value="">--Select department (optional)--</option>
            {departments.map(d => <option key={d._id} value={d._id}>{d.name} {d.type ? `(${d.type})` : ""}</option>)}
          </select>
        </div>

        <div>
          <button className="bg-blue-600 text-white px-4 py-2 rounded">Create User</button>
        </div>
      </form>
    </div>
  );
}
